import { Head, Link, useForm } from '@inertiajs/react';
import TeacherLayout from '@/Layouts/TeacherLayout';
import TextField from '@/Components/TextField';
import SelectField from '@/Components/SelectField';
import { digitsOnly, personName } from '@/lib/inputFilters';

export default function TeacherStudentForm({ sections }) {
    const { data, setData, post, processing, errors } = useForm({ first_name: '', last_name: '', lrn: '', gender: '', birthdate: '', section_id: '' });
    return <TeacherLayout title="Add Student"><Head title="Add Student" /><form onSubmit={(event) => { event.preventDefault(); post(route('teacher.students.store')); }} className="max-w-2xl space-y-5 rounded-xl bg-white p-6 shadow-sm ring-1 ring-gray-200"><p className="text-sm text-gray-500">Students can only be added to a section assigned to you. Biometric consent must be collected separately.</p><div className="grid grid-cols-1 gap-5 sm:grid-cols-2"><TextField label="First Name" value={data.first_name} onChange={(e) => setData('first_name', personName(e.target.value))} error={errors.first_name} /><TextField label="Last Name" value={data.last_name} onChange={(e) => setData('last_name', personName(e.target.value))} error={errors.last_name} /><TextField label="LRN" value={data.lrn} onChange={(e) => setData('lrn', digitsOnly(e.target.value))} error={errors.lrn} inputMode="numeric" /><SelectField label="Gender" value={data.gender} onChange={(e) => setData('gender', e.target.value)} error={errors.gender}><option value="">— Select —</option><option value="male">Male</option><option value="female">Female</option></SelectField><TextField label="Birthdate" type="date" value={data.birthdate} onChange={(e) => setData('birthdate', e.target.value)} error={errors.birthdate} /><SelectField label="Section" value={data.section_id} onChange={(e) => setData('section_id', e.target.value)} error={errors.section_id}><option value="">— Select —</option>{sections.map((section) => <option key={section.id} value={section.id}>{section.grade_level} - {section.name}</option>)}</SelectField></div><div className="flex items-center gap-3"><button type="submit" disabled={processing} className="rounded-lg bg-blue-600 px-4 py-2 font-semibold text-white hover:bg-blue-700 disabled:opacity-50">Save</button><Link href={route('teacher.students.index')} className="text-sm text-gray-500 hover:underline">Cancel</Link></div></form></TeacherLayout>;
}
